SELECT * FROM hr.employees;

-- 1
SELECT MAX(SALARY) FROM hr.employees;

-- 2
SELECT MAX(SALARY) - MIN(SALARY) FROM hr.employees;

-- 3
SELECT JOB_ID, ROUND(AVG(SALARY)) AS 'AVERAGE_SALARY' FROM hr.employees
	GROUP BY JOB_ID
    ORDER BY AVERAGE_SALARY DESC;

-- 4
SELECT SUM(SALARY) AS 'TOTAL_SALARY_COST' FROM hr.employees;

-- 5
SELECT
	ROUND(MAX(SALARY), 2) AS 'MAX_SALARY',
    ROUND(MIN(SALARY), 2) AS 'MIN_SALARY',
    ROUND(SUM(SALARY), 2) AS 'TOTAL_SALARY_COST',
    ROUND(AVG(SALARY), 2) AS 'AVERAGE_SALARY'
	FROM hr.employees;

-- 6
SELECT JOB_ID, COUNT(*) AS 'WORKERS_QUANTITY' FROM hr.employees
	GROUP BY JOB_ID
    HAVING JOB_ID = 'IT_PROG';

-- 7
SELECT JOB_ID, SUM(SALARY) AS 'TOTAL_SALARY_COST' FROM hr.employees
	GROUP BY JOB_ID;

-- 8
SELECT JOB_ID, SUM(SALARY) AS 'TOTAL_SALARY_COST' FROM hr.employees
	GROUP BY JOB_ID
    HAVING JOB_ID = 'IT_PROG';

-- 9
SELECT JOB_ID, AVG(SALARY) AS 'AVERAGE_SALARY' FROM hr.employees
	GROUP BY JOB_ID
    HAVING JOB_ID != 'IT_PROG'
    ORDER BY AVERAGE_SALARY DESC;

-- 10
SELECT AVG(SALARY) AS 'AVERAGE_SALARY', COUNT(*) 'NUMBER_OF_EMPLOYEES'
	FROM hr.employees
    GROUP BY DEPARTMENT_ID
    HAVING NUMBER_OF_EMPLOYEES > 10;
    
-- 11
SELECT REPLACE(PHONE_NUMBER, 515, 777) FROM hr.employees;

-- 12
SELECT * FROM hr.employees
	WHERE CHAR_LENGTH(FIRST_NAME) >= 8;
    
-- 13
SELECT EMPLOYEE_ID, FIRST_NAME, YEAR(HIRE_DATE) FROM hr.employees;

-- 14
SELECT EMPLOYEE_ID, FIRST_NAME, DAY(HIRE_DATE) FROM hr.employees;

-- 15
SELECT EMPLOYEE_ID, FIRST_NAME, MONTH(HIRE_DATE) FROM hr.employees;

-- 16
SELECT UCASE(CONCAT(FIRST_NAME, ' ', LAST_NAME)) AS 'FULL_NAME' FROM hr.employees;

-- 17
SELECT LAST_NAME, HIRE_DATE FROM hr.employees
	WHERE HIRE_DATE LIKE '1987-07-__';

-- 18
SELECT FIRST_NAME, LAST_NAME, DATEDIFF(CURDATE(), HIRE_DATE) AS 'DAYS_WORKED' FROM hr.employees;