const STATUS_OK = 200;
const STATUS_NOT_FOUND = 404;
const STATUS_CREATED = 201;
const STATUS_NO_CONTENT = 204;

module.exports = {
  STATUS_OK,
  STATUS_NOT_FOUND,
  STATUS_CREATED,
  STATUS_NO_CONTENT
}